### ISSUE TITLE
wrap script in path lookup

### ISSUE THREAD

**Issue by thedannywahl** [lyonsinbeta/canvas-show-student-total-activity#2]
You should wrap the script in a path lookup to prevent an api call on every page for every student.  You can place it either before or after your `if` that looks at roles.

``` lang-javascript
if(window.location.pathname == "/desired/subpath/sub-subpath") {}
```

or if you need to parse it as an array

``` lang-javascript
var path = window.location.pathname.split( '/' );
if((path[1] == "desired") && (path[3] == "sub-subpath")) {}
```

**Comment by lyonsinbeta** [comment]
Good thinking.

Fixed by [this commit](https://github.com/lyonsinbeta/canvas-show-student-total-activity/commit/6d90ef9f47cbde202da80146547258da3c45773b).
